<!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-app.js"></script>

<!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
<script src="https://www.gstatic.com/firebasejs/8.0.2/firebase-analytics.js"></script>

<script>
  // Your web app's Firebase configuration
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  var firebaseConfig = {
    apiKey: "AIzaSyA0rtyuJwtwFAZwMpDLXHOb_PkIJ1s3ozY",
    authDomain: "chatbox-a81c7.firebaseapp.com",
    databaseURL: "https://chatbox-a81c7.firebaseio.com",
    projectId: "chatbox-a81c7",
    storageBucket: "chatbox-a81c7.appspot.com",
    messagingSenderId: "718523871702",
    appId: "1:718523871702:web:6f07486b5b64e418c73477",
    measurementId: "G-T79JRNLMPG"
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  firebase.analytics();
</script>
